buildscript {
    ext.arouter_register_version = '1.0.3'

    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
        classpath "com.social.arouter:arouter-register:$arouter_register_version"
    }
}

plugins {
    id 'com.android.application' version '8.0.2' apply false
    id 'com.android.library' version '8.0.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.9.24' apply false
    id 'org.jetbrains.kotlin.kapt' version '1.9.24' apply false
}
